AWSTemplateFormatVersion: '2010-09-09'
Metadata: 
  License: Apache-2.0
Description: Building on AWS IAM User Stack
Parameters:
  Password:
    NoEcho: 'true'
    Type: String
    Description: New account password
    MinLength: '1'
    MaxLength: '41'
    ConstraintDescription: the password must be between 1 and 41 characters
Resources:
  edXDeployingPolicy:
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName: edXDeployingPolicy
      Users:
        - !Ref edXDeployingUser     
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Action: 
              - iam:*
              - elasticbeanstalk:*
              - ec2:*
              - ecs:*
              - ecr:*
              - elasticloadbalancing:*
              - autoscaling:*
              - cloudwatch:*
              - s3:*
              - sns:*
              - cloudformation:*
              - dynamodb:*
              - rds:*
              - sqs:*
              - logs:*
              - events:*
              - cloud9:*
              - codecommit:*
              - codebuild:*
              - codepipeline:*
              - codedeploy:*
              - ssm:*
              - es:*
              - lambda:*
              - tag:GetResources
              - kms:ListKeyPolicies
              - kms:GenerateRandom
              - kms:ListRetirableGrants
              - kms:GetKeyPolicy
              - kms:ListResourceTags
              - kms:ReEncryptFrom
              - kms:ListGrants
              - kms:GetParametersForImport
              - kms:ListKeys
              - kms:GetKeyRotationStatus
              - kms:ListAliases
              - kms:ReEncryptTo
              - kms:DescribeKey
            Resource: "*"

          
  edXDeployingUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: !Ref 'Password'
        PasswordResetRequired: false
      UserName: edXDeployingUser
      
  AccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref 'edXDeployingUser'
      

Outputs:
  EdXDeployingUser:
    Value: !GetAtt edXDeployingUser.Arn
  AccessKey:
    Value: !Ref 'AccessKey'
    Description: AWSAccessKeyId of new user
  SecretKey:
    Value: !GetAtt [AccessKey, SecretAccessKey]
    Description: AWSSecretKey of new user