AWSTemplateFormatVersion: '2010-09-09'
Metadata: 
  License: Apache-2.0
Description: Deploying on AWS Stack CodeCommit
Resources:
  CodeCommit:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: edX-Deploying
      RepositoryDescription: edX-Deploying
Outputs:
  GitCloneUrlHttp:
    Value: !GetAtt CodeCommit.CloneUrlHttp